### ISSUE TITLE
add access to MCMC burnin/interval control parameters

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergmLite#31] opened 2019-12-02 18:28 UTC
In the context of large nets with small subgroups, it is sometimes necessary to increase the MCMC burnin during simulation to ensure the formation of rare ties keeps up with dissolution. 

The current implementation of [`stergm_getMCMCsample`](https://github.com/statnet/tergmLite/blob/d4b3ff5c1e8742ff5b0e9e8333aa8b384019d417/R/simulate.R#L50) does not provide access to these MCMC control parameters, but it seems like a small change would make that possible.

**Comment by smjenness** [comment] 2020-04-14 20:39
Duplicate of #37

**Closed as completed by smjenness** 2020-04-14 20:39 UTC
