### ISSUE TITLE
Allow controls to be passed to simulate_network

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergmLite#37] opened 2020-02-18 22:25 UTC
Currently, it is not possible to send control arguments to the `simulate_network` function.  It is instead hardcoded in the `simulation.R` script here:

https://github.com/statnet/tergmLite/blob/b9895642b2bc7d8455dfc18494db4782cbb06272/R/simulate.R#L78

and here:

https://github.com/statnet/tergmLite/blob/b9895642b2bc7d8455dfc18494db4782cbb06272/R/simulate.R#L84-L88

Ideally, we would want to be able to set some of the control parameters, for example, when the estimation/netdx process demonstrates the need for longer intervals to match target stats.

And ideally, this could be taken from the `ergm` fit object in `dat$nwparam`, but this may require including parts of the fit object that are now stripped out in `EpiModel/net.mod.init.R` here:

https://github.com/statnet/EpiModel/blob/97da74ca9a0bb6cbfdb1b3d555de4bed07af44b4/R/net.mod.init.R#L49

**Comment by sgoodreau** [comment] 2020-04-01 21:10
@smjenness  We are diving into this on our end, as the issue is re-appearing in a number of folk's workflows.  Before we (meaning @chad-klumb) spends time thinking about how to make this happen and implmenting, we wanted to check with you - is this an avenue you already went down when you first set up tergmLite and faced issues in doing so? And/or, any down sides you see to this?

**Comment by smjenness** [comment] 2020-04-01 23:29
Haven't had any need, or given it any thought, so code away!

**Comment by sgoodreau** [comment] 2020-04-01 23:31
Great, @smjenness. @chad-klumb, it is fully in your hands.  Go forth!

**Comment by chad-klumb** [comment] 2020-08-26 13:17
This is available with `tergmLite-private@dev` and `EpiModel@summary_statistics` via the `MCMC_control` control argument.

**Comment by martinamorris** [comment] 2020-08-26 16:17
great thx.

**Comment by smjenness** [comment] 2021-06-07 15:47
Closing this as we get ready to merge into master.

**Closed as completed by smjenness** 2021-06-07 15:47 UTC
Labels: enhancement
